name: Deploy to ec2-user

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 3.8.231.147
        username: ec2-user
        password: ZjiOaiffDGj 
        script: |
          cd /var/www/html

          git clone  https://github.com/tishaas/Reservationapp.git
          # Fetch and pull the latest changes
          cd Reservationapp
          git reset --hard origin/main
          git fetch
          git pull

          # install dependencies
          npm install --force

          # pm2 cmd
          pm2 restart all

          
